/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module shared_alu_arbiter3 (
    input wire clk,
    input wire rst_n,

    input wire req0,
    input wire [2:0] op0,
    input wire [15:0] a0,
    input wire [15:0] b0,
    output reg done0,
    output wire [15:0] result0,

    input wire req1,
    input wire [2:0] op1,
    input wire [15:0] a1,
    input wire [15:0] b1,
    output reg done1,
    output wire [15:0] result1
);

    localparam ALU_ADD = 3'd0;
    localparam ALU_SUB = 3'd1;
    localparam ALU_AND = 3'd2;
    localparam ALU_OR  = 3'd3;
    localparam ALU_XOR = 3'd4;
    localparam ALU_SHL = 3'd5;
    localparam ALU_SHR = 3'd6;

    reg [1:0] pending;
    reg rr_ptr;
    reg [15:0] shared_result;

    reg grant_valid;
    reg grant_idx;

    reg [2:0]  sel_op;
    reg [15:0] sel_a;
    reg [15:0] sel_b;

    assign result0 = shared_result;
    assign result1 = shared_result;

    function [15:0] alu_calc;
        input [2:0] op;
        input [15:0] a;
        input [15:0] b;
        begin
            case (op)
                ALU_ADD: alu_calc = a + b;
                ALU_SUB: alu_calc = a - b;
                ALU_AND: alu_calc = a & b;
                ALU_OR:  alu_calc = a | b;
                ALU_XOR: alu_calc = a ^ b;
                ALU_SHL: alu_calc = a << b[3:0];
                ALU_SHR: alu_calc = a >> b[3:0];
                default: alu_calc = 16'd0;
            endcase
        end
    endfunction

    always @(*) begin
        grant_valid = 1'b0;
        grant_idx   = 1'b0;

        case (rr_ptr)
            1'b0: begin
                if (pending[0]) begin grant_valid = 1'b1; grant_idx = 1'b0; end
                else if (pending[1]) begin grant_valid = 1'b1; grant_idx = 1'b1; end
            end
            default: begin
                if (pending[1]) begin grant_valid = 1'b1; grant_idx = 1'b1; end
                else if (pending[0]) begin grant_valid = 1'b1; grant_idx = 1'b0; end
            end
        endcase
    end

    always @(*) begin
        case (grant_idx)
            1'b0: begin sel_op = op0; sel_a = a0; sel_b = b0; end
            default: begin sel_op = op1; sel_a = a1; sel_b = b1; end
        endcase
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            pending       <= 2'd0;
            rr_ptr        <= 1'b0;
            done0         <= 1'b0;
            done1         <= 1'b0;
            shared_result <= 16'd0;
        end else begin
            done0 <= 1'b0;
            done1 <= 1'b0;

            if (req0 && !pending[0]) pending[0] <= 1'b1;
            if (req1 && !pending[1]) pending[1] <= 1'b1;

            if (grant_valid) begin
                shared_result <= alu_calc(sel_op, sel_a, sel_b);
                case (grant_idx)
                    1'b0: begin done0 <= 1'b1; pending[0] <= 1'b0; rr_ptr <= 1'b1; end
                    default: begin done1 <= 1'b1; pending[1] <= 1'b0; rr_ptr <= 1'b0; end
                endcase
            end
        end
    end

endmodule
module shared_event_unit3 (
    input wire clk,
    input wire rst_n,

    input wire set0,
    input wire clr0,
    input wire [2:0] id0,

    input wire set1,
    input wire clr1,
    input wire [2:0] id1,

    input wire set2,
    input wire clr2,
    input wire [2:0] id2,

    output reg [7:0] event_flags
);

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            event_flags <= 8'd0;
        end else begin
            // clear first, then set, so SET wins if both happen in one cycle
            if (clr0) event_flags[id0] <= 1'b0;
            if (clr1) event_flags[id1] <= 1'b0;
            if (clr2) event_flags[id2] <= 1'b0;

            if (set0) event_flags[id0] <= 1'b1;
            if (set1) event_flags[id1] <= 1'b1;
            if (set2) event_flags[id2] <= 1'b1;
        end
    end

endmodule
module tiny_core (
    input  wire  [15:0] RESET_PC,
    input  wire        clk,
    input  wire        rst_n,

    input  wire        core_en,

    // shared ALU style interface
    output reg         alu_req,
    output reg  [2:0]  alu_op,
    output reg  [15:0] alu_a,
    output reg  [15:0] alu_b,
    input  wire        alu_done,
    input  wire [15:0] alu_result,

    // shared memory bus style interface
    output reg         mem_req,
    output reg         mem_write,
    output reg         mem_target,   // 0 = flash, 1 = RAM
    output reg  [15:0] mem_addr,
    output reg  [15:0] mem_wdata,
    input  wire        mem_done,
    input  wire [15:0] mem_rdata,

    // simple output
    output reg  [15:0] out_reg,
    output reg         halted,

    // shared event system
    output reg         event_set,
    output reg         event_clr,
    output reg  [2:0]  event_id,
    input  wire [7:0]  event_flags,

    // separate pin controller interface
    output reg         pin_req,
    output reg  [1:0]  pin_op,
    output reg  [2:0]  pin_id,
    output reg         pin_wdata,
    input  wire        pin_done,
    input  wire [15:0] pin_rdata,

    // separate UART controller interface
    output reg         uart_req,
    output reg  [1:0]  uart_op,
    output reg  [15:0] uart_wdata,
    input  wire        uart_done,
    input  wire [15:0] uart_rdata,

    // debug
    output wire [15:0] debug_pc,
    output wire [15:0] debug_r0,
    output wire [15:0] debug_r1,
    output wire [15:0] debug_r2,
    output wire [15:0] debug_r3
  );

  // 5-bit opcodes
  localparam OP_NOP     = 5'd0;
  localparam OP_HALT    = 5'd1;
  localparam OP_LDI     = 5'd2;
  localparam OP_MOV     = 5'd3;
  localparam OP_ADD     = 5'd4;
  localparam OP_SUB     = 5'd5;
  localparam OP_JMP     = 5'd6;
  localparam OP_JZ      = 5'd7;
  localparam OP_RESV08  = 5'd8;  // was OUT
  localparam OP_LD      = 5'd9;
  localparam OP_ST      = 5'd10;
  localparam OP_AND     = 5'd11;
  localparam OP_OR      = 5'd12;
  localparam OP_XOR     = 5'd13;
  localparam OP_SHL     = 5'd14;
  localparam OP_SHR     = 5'd15;
  localparam OP_IMMLO   = 5'd16;
  localparam OP_IMMHI   = 5'd17;
  localparam OP_LDIM    = 5'd18;
  localparam OP_SETEV   = 5'd19;
  localparam OP_CLREV   = 5'd20;
  localparam OP_WAITEV  = 5'd21;
  localparam OP_JMPR    = 5'd22;
  localparam OP_WAITPIN = 5'd23;
  localparam OP_IN      = 5'd24;
  localparam OP_SETPIN  = 5'd25;
  localparam OP_UART    = 5'd26; // was GETPIN
  localparam OP_JNZ     = 5'd27;
  localparam OP_LDF     = 5'd28;
  localparam OP_LDREG   = 5'd29;
  localparam OP_STREG   = 5'd30;
  localparam OP_SLEEP   = 5'd31;

  // ALU ops
  localparam ALU_ADD = 3'd0;
  localparam ALU_SUB = 3'd1;
  localparam ALU_AND = 3'd2;
  localparam ALU_OR  = 3'd3;
  localparam ALU_XOR = 3'd4;
  localparam ALU_SHL = 3'd5;
  localparam ALU_SHR = 3'd6;

  // pin controller ops
  localparam PIN_OP_READ_ALL  = 2'd0;
  localparam PIN_OP_WRITE_PIN = 2'd2;
  localparam PIN_OP_WAIT_PIN  = 2'd3;

  // UART controller ops, selected by instr[6:5]
  localparam UART_OP_STATUS = 2'd0; // read status into rd
  localparam UART_OP_TX     = 2'd1; // attempt TX from rd[7:0]
  localparam UART_OP_RX     = 2'd2; // read RX into rd, rd[15]=valid
  localparam UART_OP_BAUD   = 2'd3; // baud_div <= rd

  // states
  localparam ST_FETCH      = 4'd0;
  localparam ST_WAIT_FETCH = 4'd1;
  localparam ST_DECODE     = 4'd2;
  localparam ST_WAIT_ALU   = 4'd3;
  localparam ST_WAIT_MEM   = 4'd4;
  localparam ST_HALTED     = 4'd5;
  localparam ST_WAIT_PIN   = 4'd6;
  localparam ST_SLEEP      = 4'd7;
  localparam ST_WAIT_UART  = 4'd8;

  reg [3:0]  state;
  reg [15:0] pc;
  reg [15:0] instr;
  reg [15:0] imm_reg;
  reg [7:0]  sleep_count;

  reg [15:0] r0;
  reg [15:0] r1;
  reg [15:0] r2;
  reg [15:0] r3;

  reg [1:0] pending_rd;
  reg       pending_mem_write;
  reg       pending_pin_read;

  wire [4:0]  opcode;
  wire [1:0]  rd;
  wire [1:0]  ra;
  wire [1:0]  rb;
  wire [7:0]  imm8;
  wire [10:0] imm11;
  wire [6:0]  imm7;
  wire [2:0]  ev_id;
  wire        pin_val;
  wire [1:0]  uart_subop;
  wire [15:0] rel11;
  wire [15:0] rel7;

  reg [15:0] rd_value;
  reg [15:0] ra_value;
  reg [15:0] rb_value;
  reg        event_selected;

  assign opcode  = instr[15:11];
  assign rd      = instr[10:9];
  assign ra      = instr[8:7];
  assign rb      = instr[6:5];
  assign imm8    = instr[7:0];
  assign imm11   = instr[10:0];
  assign imm7    = instr[6:0];
  assign ev_id   = instr[2:0];
  assign pin_val = instr[3];
  assign uart_subop = instr[6:5];

  assign rel11 = {{5{imm11[10]}}, imm11};
  assign rel7  = {{9{imm7[6]}}, imm7};

  assign debug_pc = pc;
  assign debug_r0 = r0;
  assign debug_r1 = r1;
  assign debug_r2 = r2;
  assign debug_r3 = r3;

  always @(*)
  begin
    case (rd)
      2'd0: rd_value = r0;
      2'd1: rd_value = r1;
      2'd2: rd_value = r2;
      2'd3: rd_value = r3;
      default: rd_value = 16'd0;
    endcase

    case (ra)
      2'd0: ra_value = r0;
      2'd1: ra_value = r1;
      2'd2: ra_value = r2;
      2'd3: ra_value = r3;
      default: ra_value = 16'd0;
    endcase

    case (rb)
      2'd0: rb_value = r0;
      2'd1: rb_value = r1;
      2'd2: rb_value = r2;
      2'd3: rb_value = r3;
      default: rb_value = 16'd0;
    endcase

    case (ev_id)
      3'd0: event_selected = event_flags[0];
      3'd1: event_selected = event_flags[1];
      3'd2: event_selected = event_flags[2];
      3'd3: event_selected = event_flags[3];
      3'd4: event_selected = event_flags[4];
      3'd5: event_selected = event_flags[5];
      3'd6: event_selected = event_flags[6];
      3'd7: event_selected = event_flags[7];
      default: event_selected = 1'b0;
    endcase  end

  always @(posedge clk or negedge rst_n)
  begin
    if (!rst_n)
    begin
      pc         <= RESET_PC;
      instr      <= 16'd0;
      state      <= ST_FETCH;

      r0         <= 16'd0;
      r1         <= 16'd0;
      r2         <= 16'd0;
      r3         <= 16'd0;
      imm_reg    <= 16'd0;
      sleep_count <= 8'd0;

      pending_rd        <= 2'd0;
      pending_mem_write <= 1'b0;
      pending_pin_read  <= 1'b0;

      alu_req    <= 1'b0;
      alu_op     <= 3'd0;
      alu_a      <= 16'd0;
      alu_b      <= 16'd0;

      mem_req    <= 1'b0;
      mem_write  <= 1'b0;
      mem_target <= 1'b1;
      mem_addr   <= 16'd0;
      mem_wdata  <= 16'd0;

      out_reg    <= 16'd0;
      halted     <= 1'b0;

      event_set <= 1'b0;
      event_clr <= 1'b0;
      event_id  <= 3'd0;

      pin_req   <= 1'b0;
      pin_op    <= 2'd0;
      pin_id    <= 3'd0;
      pin_wdata <= 1'b0;

      uart_req   <= 1'b0;
      uart_op    <= 2'd0;
      uart_wdata <= 16'd0;
    end
    else
    begin
      alu_req   <= 1'b0;
      mem_req   <= 1'b0;
      event_set <= 1'b0;
      event_clr <= 1'b0;
      pin_req   <= 1'b0;
      uart_req  <= 1'b0;

      if (state == ST_WAIT_FETCH)
      begin
        if (mem_done)
        begin
          instr <= mem_rdata;
          state <= ST_DECODE;
        end
        else
        begin
          // Hold fetch request until granted/done. This lets the memory
          // arbiter avoid storing every core's addr/data request.
          mem_req    <= 1'b1;
          mem_write  <= 1'b0;
          mem_target <= 1'b0; // flash
          mem_addr   <= pc;
          mem_wdata  <= 16'd0;
        end
      end
      else if (state == ST_WAIT_ALU)
      begin
        if (alu_done)
        begin
          case (pending_rd)
            2'd0: r0 <= alu_result;
            2'd1: r1 <= alu_result;
            2'd2: r2 <= alu_result;
            2'd3: r3 <= alu_result;
          endcase

          pc    <= pc + 16'd1;
          state <= ST_FETCH;
        end
      end
      else if (state == ST_WAIT_MEM)
      begin
        if (mem_done)
        begin
          if (!pending_mem_write)
          begin
            case (pending_rd)
              2'd0: r0 <= mem_rdata;
              2'd1: r1 <= mem_rdata;
              2'd2: r2 <= mem_rdata;
              2'd3: r3 <= mem_rdata;
            endcase
          end

          pc    <= pc + 16'd1;
          state <= ST_FETCH;
        end
        else
        begin
          // Hold data memory request until granted/done.
          mem_req <= 1'b1;

          if ((opcode == OP_ST) || (opcode == OP_STREG))
          begin
            mem_write  <= 1'b1;
            mem_target <= 1'b1; // RAM
            if (opcode == OP_STREG)
              mem_addr <= ra_value;
            else
              mem_addr <= {8'd0, imm8};
            mem_wdata  <= rd_value;
          end
          else if (opcode == OP_LDF)
          begin
            mem_write  <= 1'b0;
            mem_target <= 1'b0; // flash
            mem_addr   <= imm_reg;
            mem_wdata  <= 16'd0;
          end
          else if (opcode == OP_LDREG)
          begin
            mem_write  <= 1'b0;
            mem_target <= 1'b1; // RAM
            mem_addr   <= ra_value;
            mem_wdata  <= 16'd0;
          end
          else
          begin
            // OP_LD
            mem_write  <= 1'b0;
            mem_target <= 1'b1; // RAM
            mem_addr   <= {8'd0, imm8};
            mem_wdata  <= 16'd0;
          end
        end
      end
      else if (state == ST_WAIT_PIN)
      begin
        pin_req <= 1'b1;

        if (pin_done)
        begin
          if (pending_pin_read)
          begin
            case (pending_rd)
              2'd0: r0 <= pin_rdata;
              2'd1: r1 <= pin_rdata;
              2'd2: r2 <= pin_rdata;
              2'd3: r3 <= pin_rdata;
            endcase
          end

          pc    <= pc + 16'd1;
          state <= ST_FETCH;
        end
      end
      else if (state == ST_SLEEP)
      begin
        if (sleep_count == 8'd0)
        begin
          pc    <= pc + 16'd1;
          state <= ST_FETCH;
        end
        else
        begin
          sleep_count <= sleep_count - 8'd1;
        end
      end
      else if (state == ST_WAIT_UART)
      begin
        uart_req   <= 1'b1;
        uart_op    <= uart_subop;
        uart_wdata <= rd_value;

        if (uart_done)
        begin
          if ((uart_subop == UART_OP_STATUS) || (uart_subop == UART_OP_RX))
          begin
            case (pending_rd)
              2'd0: r0 <= uart_rdata;
              2'd1: r1 <= uart_rdata;
              2'd2: r2 <= uart_rdata;
              2'd3: r3 <= uart_rdata;
            endcase
          end

          pc    <= pc + 16'd1;
          state <= ST_FETCH;
        end
      end
      else if (core_en && !halted)
      begin
        case (state)
          ST_FETCH:
          begin
            // Enter wait state first; ST_WAIT_FETCH holds the actual request.
            pending_rd        <= 2'd0;
            pending_mem_write <= 1'b0;
            state             <= ST_WAIT_FETCH;
          end

          ST_DECODE:
          begin
            case (opcode)
              OP_NOP:
              begin
                pc    <= pc + 16'd1;
                state <= ST_FETCH;
              end

              OP_HALT:
              begin
                halted <= 1'b1;
                state  <= ST_HALTED;
              end

              OP_LDI:
              begin
                case (rd)
                  2'd0: r0 <= {8'd0, imm8};
                  2'd1: r1 <= {8'd0, imm8};
                  2'd2: r2 <= {8'd0, imm8};
                  2'd3: r3 <= {8'd0, imm8};
                endcase
                pc    <= pc + 16'd1;
                state <= ST_FETCH;
              end

              OP_MOV:
              begin
                case (rd)
                  2'd0: r0 <= ra_value;
                  2'd1: r1 <= ra_value;
                  2'd2: r2 <= ra_value;
                  2'd3: r3 <= ra_value;
                endcase
                pc    <= pc + 16'd1;
                state <= ST_FETCH;
              end

              OP_ADD, OP_SUB, OP_AND, OP_OR, OP_XOR, OP_SHL, OP_SHR:
              begin
                alu_req    <= 1'b1;
                alu_a      <= ra_value;
                alu_b      <= rb_value;
                pending_rd <= rd;
                state      <= ST_WAIT_ALU;

                case (opcode)
                  OP_ADD: alu_op <= ALU_ADD;
                  OP_SUB: alu_op <= ALU_SUB;
                  OP_AND: alu_op <= ALU_AND;
                  OP_OR:  alu_op <= ALU_OR;
                  OP_XOR: alu_op <= ALU_XOR;
                  OP_SHL: alu_op <= ALU_SHL;
                  OP_SHR: alu_op <= ALU_SHR;
                  default: alu_op <= ALU_ADD;
                endcase
              end

              OP_JMP:
              begin
                // PC-relative jump: target = pc + 1 + signext11(imm11)
                pc    <= pc + 16'd1 + rel11;
                state <= ST_FETCH;
              end

              OP_JZ:
              begin
                // PC-relative branch: target = pc + 1 + signext7(imm7)
                if (ra_value == 16'd0)
                  pc <= pc + 16'd1 + rel7;
                else
                  pc <= pc + 16'd1;
                state <= ST_FETCH;
              end

              OP_JNZ:
              begin
                // PC-relative branch: target = pc + 1 + signext7(imm7)
                if (ra_value != 16'd0)
                  pc <= pc + 16'd1 + rel7;
                else
                  pc <= pc + 16'd1;
                state <= ST_FETCH;
              end
              OP_LD:
              begin
                pending_rd        <= rd;
                pending_mem_write <= 1'b0;
                state             <= ST_WAIT_MEM;
              end

              OP_ST:
              begin
                pending_rd        <= 2'd0;
                pending_mem_write <= 1'b1;
                state             <= ST_WAIT_MEM;
              end

              OP_IMMLO:
              begin
                imm_reg[7:0] <= imm8;
                pc           <= pc + 16'd1;
                state        <= ST_FETCH;
              end

              OP_IMMHI:
              begin
                imm_reg[15:8] <= imm8;
                pc            <= pc + 16'd1;
                state         <= ST_FETCH;
              end

              OP_LDIM:
              begin
                case (rd)
                  2'd0: r0 <= imm_reg;
                  2'd1: r1 <= imm_reg;
                  2'd2: r2 <= imm_reg;
                  2'd3: r3 <= imm_reg;
                endcase
                pc    <= pc + 16'd1;
                state <= ST_FETCH;
              end

              OP_SETEV:
              begin
                event_set <= 1'b1;
                event_id  <= ev_id;
                pc        <= pc + 16'd1;
                state     <= ST_FETCH;
              end

              OP_CLREV:
              begin
                event_clr <= 1'b1;
                event_id  <= ev_id;
                pc        <= pc + 16'd1;
                state     <= ST_FETCH;
              end

              OP_WAITEV:
              begin
                event_id <= ev_id;
                if (event_selected)
                begin
                  pc    <= pc + 16'd1;
                  state <= ST_FETCH;
                end
                else
                begin
                  state <= ST_DECODE;
                end
              end

              OP_JMPR:
              begin
                pc    <= ra_value;
                state <= ST_FETCH;
              end

              OP_WAITPIN:
              begin
                pin_req          <= 1'b1;
                pin_op           <= PIN_OP_WAIT_PIN;
                pin_id           <= ev_id;
                pin_wdata        <= pin_val;
                pending_rd       <= 2'd0;
                pending_pin_read <= 1'b0;
                state            <= ST_WAIT_PIN;
              end

              OP_IN:
              begin
                pin_req          <= 1'b1;
                pin_op           <= PIN_OP_READ_ALL;
                pin_id           <= 3'd0;
                pin_wdata        <= 1'b0;
                pending_rd       <= rd;
                pending_pin_read <= 1'b1;
                state            <= ST_WAIT_PIN;
              end

              OP_SETPIN:
              begin
                pin_req          <= 1'b1;
                pin_op           <= PIN_OP_WRITE_PIN;
                pin_id           <= ev_id;
                pin_wdata        <= pin_val;
                pending_rd       <= 2'd0;
                pending_pin_read <= 1'b0;
                state            <= ST_WAIT_PIN;
              end
              OP_UART:
              begin
                uart_req   <= 1'b1;
                uart_op    <= uart_subop;
                uart_wdata <= rd_value;
                pending_rd <= rd;
                state      <= ST_WAIT_UART;
              end

              OP_LDF:
              begin
                pending_rd        <= rd;
                pending_mem_write <= 1'b0;
                state             <= ST_WAIT_MEM;
              end

              OP_LDREG:
              begin
                pending_rd        <= rd;
                pending_mem_write <= 1'b0;
                state             <= ST_WAIT_MEM;
              end

              OP_STREG:
              begin
                pending_rd        <= 2'd0;
                pending_mem_write <= 1'b1;
                state             <= ST_WAIT_MEM;
              end

              OP_SLEEP:
              begin
                sleep_count <= imm8;
                state       <= ST_SLEEP;
              end

              default:
              begin
                halted <= 1'b1;
                state  <= ST_HALTED;
              end
            endcase
          end

          ST_HALTED:
          begin
            halted <= 1'b1;
          end

          default:
          begin
            state <= ST_FETCH;
          end
        endcase
      end
    end
  end

endmodule

module shared_spi_mem_arbiter3 (
    input wire clk,
    input wire rst_n,

    input wire req0,
    input wire write0,
    input wire target0,          // 0 = flash, 1 = RAM
    input wire [15:0] addr0,
    input wire [15:0] wdata0,
    output reg done0,
    output reg [15:0] rdata0,

    input wire req1,
    input wire write1,
    input wire target1,
    input wire [15:0] addr1,
    input wire [15:0] wdata1,
    output reg done1,
    output reg [15:0] rdata1,

    input wire req2,
    input wire write2,
    input wire target2,
    input wire [15:0] addr2,
    input wire [15:0] wdata2,
    output reg done2,
    output reg [15:0] rdata2,

    // qspi_memory_interface side
    input wire        spi_ready,
    output reg        spi_st,
    output reg        spi_ld,
    output reg        spi_target,
    output reg [15:0] spi_addr,
    output reg [15:0] spi_data_in,
    input wire [15:0] spi_data_out,
    input wire        spi_busy
  );

  localparam S_IDLE           = 3'd0;
  localparam S_START          = 3'd1;
  localparam S_WAIT_BUSY_HIGH = 3'd2;
  localparam S_WAIT_BUSY_LOW  = 3'd3;
  localparam S_FINISH         = 3'd4;
  localparam S_COOLDOWN       = 3'd5;

  reg [2:0] state;

  reg [1:0] rr_ptr;
  reg [1:0] active_idx;
  reg       active_write;
  reg [15:0] active_wdata;

  reg grant_valid;
  reg [1:0] grant_idx;

  reg sel_write;
  reg sel_target;
  reg [15:0] sel_addr;
  reg [15:0] sel_wdata;

  always @(*)
  begin
    grant_valid = 1'b0;
    grant_idx   = 2'd0;

    case (rr_ptr)
      2'd0:
      begin
        if (req0) begin grant_valid = 1'b1; grant_idx = 2'd0; end
        else if (req1) begin grant_valid = 1'b1; grant_idx = 2'd1; end
        else if (req2) begin grant_valid = 1'b1; grant_idx = 2'd2; end
      end

      2'd1:
      begin
        if (req1) begin grant_valid = 1'b1; grant_idx = 2'd1; end
        else if (req2) begin grant_valid = 1'b1; grant_idx = 2'd2; end
        else if (req0) begin grant_valid = 1'b1; grant_idx = 2'd0; end
      end

      default:
      begin
        if (req2) begin grant_valid = 1'b1; grant_idx = 2'd2; end
        else if (req0) begin grant_valid = 1'b1; grant_idx = 2'd0; end
        else if (req1) begin grant_valid = 1'b1; grant_idx = 2'd1; end
      end
    endcase
  end

  always @(*)
  begin
    case (grant_idx)
      2'd0:
      begin
        sel_write  = write0;
        sel_target = target0;
        sel_addr   = addr0;
        sel_wdata  = wdata0;
      end

      2'd1:
      begin
        sel_write  = write1;
        sel_target = target1;
        sel_addr   = addr1;
        sel_wdata  = wdata1;
      end

      default:
      begin
        sel_write  = write2;
        sel_target = target2;
        sel_addr   = addr2;
        sel_wdata  = wdata2;
      end
    endcase
  end

  always @(posedge clk or negedge rst_n)
  begin
    if (!rst_n)
    begin
      state <= S_IDLE;

      rr_ptr  <= 2'd0;
      active_idx <= 2'd0;
      active_write <= 1'b0;
      active_wdata <= 16'd0;

      done0 <= 1'b0;
      done1 <= 1'b0;
      done2 <= 1'b0;

      rdata0 <= 16'd0;
      rdata1 <= 16'd0;
      rdata2 <= 16'd0;

      spi_st      <= 1'b0;
      spi_ld      <= 1'b0;
      spi_target  <= 1'b1;
      spi_addr    <= 16'd0;
      spi_data_in <= 16'd0;
    end
    else
    begin
      done0 <= 1'b0;
      done1 <= 1'b0;
      done2 <= 1'b0;

      spi_st <= 1'b0;
      spi_ld <= 1'b0;

      case (state)
        S_IDLE:
        begin
          if (grant_valid && spi_ready)
          begin
            active_idx   <= grant_idx;
            active_write <= sel_write;
            active_wdata <= sel_wdata;
            state        <= S_START;
          end
        end

        S_START:
        begin
          // In S_START, grant_idx/sel_* still correspond to the selected
          // request because the selected core holds req high while waiting.
          spi_target  <= sel_target;
          spi_addr    <= sel_addr;
          spi_data_in <= sel_wdata;

          if (sel_write)
            spi_st <= 1'b1;
          else
            spi_ld <= 1'b1;

          state <= S_WAIT_BUSY_HIGH;
        end

        S_WAIT_BUSY_HIGH:
        begin
          if (spi_busy)
            state <= S_WAIT_BUSY_LOW;
        end

        S_WAIT_BUSY_LOW:
        begin
          if (!spi_busy)
            state <= S_FINISH;
        end

        S_FINISH:
        begin
          case (active_idx)
            2'd0:
            begin
              rdata0 <= active_write ? active_wdata : spi_data_out;
              done0  <= 1'b1;
              rr_ptr <= 2'd1;
            end

            2'd1:
            begin
              rdata1 <= active_write ? active_wdata : spi_data_out;
              done1  <= 1'b1;
              rr_ptr <= 2'd2;
            end

            default:
            begin
              rdata2 <= active_write ? active_wdata : spi_data_out;
              done2  <= 1'b1;
              rr_ptr <= 2'd0;
            end
          endcase

          // One dead cycle avoids re-granting the same stale req before the
          // core has sampled done and dropped mem_req.
          state <= S_COOLDOWN;
        end

        S_COOLDOWN:
        begin
          state <= S_IDLE;
        end

        default:
        begin
          state <= S_IDLE;
        end
      endcase
    end
  end

endmodule

module shared_pin_controller3 (
    input wire clk,
    input wire rst_n,

    // real separate pins
    input  wire [7:0] gpio_in,
    output reg  [7:0] gpio_out,

    // core 0 request
    input wire        req0,
    input wire [1:0]  op0,
    input wire [2:0]  pin0,
    input wire        wdata0,
    output reg        done0,
    output reg [15:0] rdata0,

    // core 1 request
    input wire        req1,
    input wire [1:0]  op1,
    input wire [2:0]  pin1,
    input wire        wdata1,
    output reg        done1,
    output reg [15:0] rdata1
);

    localparam PIN_OP_READ_ALL  = 2'd0;
    localparam PIN_OP_READ_PIN  = 2'd1;
    localparam PIN_OP_WRITE_PIN = 2'd2;
    localparam PIN_OP_WAIT_PIN  = 2'd3;

    reg pin_bit0;
    reg pin_bit1;

    always @(*) begin
        case (pin0)
            3'd0: pin_bit0 = gpio_in[0];
            3'd1: pin_bit0 = gpio_in[1];
            3'd2: pin_bit0 = gpio_in[2];
            3'd3: pin_bit0 = gpio_in[3];
            3'd4: pin_bit0 = gpio_in[4];
            3'd5: pin_bit0 = gpio_in[5];
            3'd6: pin_bit0 = gpio_in[6];
            3'd7: pin_bit0 = gpio_in[7];
            default: pin_bit0 = 1'b0;
        endcase

        case (pin1)
            3'd0: pin_bit1 = gpio_in[0];
            3'd1: pin_bit1 = gpio_in[1];
            3'd2: pin_bit1 = gpio_in[2];
            3'd3: pin_bit1 = gpio_in[3];
            3'd4: pin_bit1 = gpio_in[4];
            3'd5: pin_bit1 = gpio_in[5];
            3'd6: pin_bit1 = gpio_in[6];
            3'd7: pin_bit1 = gpio_in[7];
            default: pin_bit1 = 1'b0;
        endcase
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            gpio_out <= 8'd0;

            done0 <= 1'b0;
            done1 <= 1'b0;

            rdata0 <= 16'd0;
            rdata1 <= 16'd0;
        end else begin
            done0 <= 1'b0;
            done1 <= 1'b0;

            rdata0 <= 16'd0;
            rdata1 <= 16'd0;

            if (req0) begin
                case (op0)
                    PIN_OP_READ_ALL: begin
                        rdata0 <= {8'd0, gpio_in};
                        done0  <= 1'b1;
                    end

                    PIN_OP_READ_PIN: begin
                        rdata0 <= {15'd0, pin_bit0};
                        done0  <= 1'b1;
                    end

                    PIN_OP_WRITE_PIN: begin
                        case (pin0)
                            3'd0: gpio_out[0] <= wdata0;
                            3'd1: gpio_out[1] <= wdata0;
                            3'd2: gpio_out[2] <= wdata0;
                            3'd3: gpio_out[3] <= wdata0;
                            3'd4: gpio_out[4] <= wdata0;
                            3'd5: gpio_out[5] <= wdata0;
                            3'd6: gpio_out[6] <= wdata0;
                            3'd7: gpio_out[7] <= wdata0;
                        endcase
                        rdata0 <= 16'd0;
                        done0  <= 1'b1;
                    end

                    PIN_OP_WAIT_PIN: begin
                        if (pin_bit0 == wdata0) begin
                            rdata0 <= 16'd0;
                            done0  <= 1'b1;
                        end
                    end
                endcase
            end

            if (req1) begin
                case (op1)
                    PIN_OP_READ_ALL: begin
                        rdata1 <= {8'd0, gpio_in};
                        done1  <= 1'b1;
                    end

                    PIN_OP_READ_PIN: begin
                        rdata1 <= {15'd0, pin_bit1};
                        done1  <= 1'b1;
                    end

                    PIN_OP_WRITE_PIN: begin
                        case (pin1)
                            3'd0: gpio_out[0] <= wdata1;
                            3'd1: gpio_out[1] <= wdata1;
                            3'd2: gpio_out[2] <= wdata1;
                            3'd3: gpio_out[3] <= wdata1;
                            3'd4: gpio_out[4] <= wdata1;
                            3'd5: gpio_out[5] <= wdata1;
                            3'd6: gpio_out[6] <= wdata1;
                            3'd7: gpio_out[7] <= wdata1;
                        endcase
                        rdata1 <= 16'd0;
                        done1  <= 1'b1;
                    end

                    PIN_OP_WAIT_PIN: begin
                        if (pin_bit1 == wdata1) begin
                            rdata1 <= 16'd0;
                            done1  <= 1'b1;
                        end
                    end
                endcase
            end
        end
    end

endmodule

module shared_uart_controller2_event (
    input  wire        clk,
    input  wire        rst_n,

    // real UART pins
    input  wire        uart_rx,
    output wire        uart_tx,
    output wire        uart_tx_oe,

    // event output, connect to shared event unit as an extra SET source
    output wire        uart_event_set,
    output wire [2:0]  uart_event_id,

    // core 0 request
    input  wire        req0,
    input  wire [1:0]  op0,
    input  wire [15:0] wdata0,
    output reg         done0,
    output reg  [15:0] rdata0,

    // core 1 request
    input  wire        req1,
    input  wire [1:0]  op1,
    input  wire [15:0] wdata1,
    output reg         done1,
    output reg  [15:0] rdata1
);

    reg rr_ptr;

    reg        grant_valid;
    reg        grant_idx;
    reg [1:0]  sel_op;
    reg [15:0] sel_wdata;

    reg        uart_req_i;
    reg [1:0]  uart_op_i;
    reg [15:0] uart_wdata_i;
    wire       uart_done_i;
    wire [15:0] uart_rdata_i;

    always @(*) begin
        grant_valid = 1'b0;
        grant_idx   = 1'b0;

        if (rr_ptr == 1'b0) begin
            if (req0) begin grant_valid = 1'b1; grant_idx = 1'b0; end
            else if (req1) begin grant_valid = 1'b1; grant_idx = 1'b1; end
        end else begin
            if (req1) begin grant_valid = 1'b1; grant_idx = 1'b1; end
            else if (req0) begin grant_valid = 1'b1; grant_idx = 1'b0; end
        end

        if (grant_idx == 1'b0) begin
            sel_op = op0;
            sel_wdata = wdata0;
        end else begin
            sel_op = op1;
            sel_wdata = wdata1;
        end
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            rr_ptr <= 1'b0;
            done0 <= 1'b0;
            done1 <= 1'b0;
            rdata0 <= 16'd0;
            rdata1 <= 16'd0;
            uart_req_i <= 1'b0;
            uart_op_i <= 2'd0;
            uart_wdata_i <= 16'd0;
        end else begin
            done0 <= 1'b0;
            done1 <= 1'b0;
            uart_req_i <= 1'b0;

            // Nonblocking: granted command completes immediately.
            if (grant_valid) begin
                uart_req_i   <= 1'b1;
                uart_op_i    <= sel_op;
                uart_wdata_i <= sel_wdata;

                if (grant_idx == 1'b0) begin
                    done0  <= uart_done_i;
                    rdata0 <= uart_rdata_i;
                    rr_ptr <= 1'b1;
                end else begin
                    done1  <= uart_done_i;
                    rdata1 <= uart_rdata_i;
                    rr_ptr <= 1'b0;
                end
            end
        end
    end

    tiny_uart_core_nonblocking uart_core (
        .clk(clk),
        .rst_n(rst_n),

        .req(uart_req_i),
        .op(uart_op_i),
        .wdata(uart_wdata_i),
        .done(uart_done_i),
        .rdata(uart_rdata_i),

        .rx_event_set(uart_event_set),
        .rx_event_id(uart_event_id),

        .uart_rx(uart_rx),
        .uart_tx(uart_tx),
        .uart_tx_oe(uart_tx_oe)
    );

endmodule


module tiny_uart_core_nonblocking (
    input  wire        clk,
    input  wire        rst_n,

    input  wire        req,
    input  wire [1:0]  op,
    input  wire [15:0] wdata,
    output reg         done,
    output reg  [15:0] rdata,

    output reg         rx_event_set,
    output wire [2:0]  rx_event_id,

    input  wire        uart_rx,
    output reg         uart_tx,
    output wire        uart_tx_oe
);

    localparam UART_OP_STATUS = 2'd0;
    localparam UART_OP_TX     = 2'd1;
    localparam UART_OP_RX     = 2'd2;
    localparam UART_OP_BAUD   = 2'd3;

    // RX event id fixed to ev7.
    assign rx_event_id = 3'd7;

    // UART TX should drive idle high when not transmitting, so OE is always enabled.
    // If you later want half-duplex/open-drain behavior, change this to tx_busy.
    assign uart_tx_oe = tx_busy;

    reg [15:0] baud_div;

    // TX
    reg        tx_busy;
    reg [9:0]  tx_shift;
    reg [15:0] tx_baud_cnt;
    reg [3:0]  tx_bit_cnt;
    wire       tx_ready;
    assign tx_ready = !tx_busy;

    // RX
    reg [1:0]  rx_sync;
    reg        rx_busy;
    reg [15:0] rx_baud_cnt;
    reg [3:0]  rx_bit_cnt;
    reg [7:0]  rx_shift;
    reg [7:0]  rx_data;
    reg        rx_valid;
    reg        rx_overrun;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            baud_div <= 16'd433; // 50 MHz / 115200 - 1

            uart_tx <= 1'b1;
            tx_busy <= 1'b0;
            tx_shift <= 10'h3FF;
            tx_baud_cnt <= 16'd0;
            tx_bit_cnt <= 4'd0;

            rx_sync <= 2'b11;
            rx_busy <= 1'b0;
            rx_baud_cnt <= 16'd0;
            rx_bit_cnt <= 4'd0;
            rx_shift <= 8'd0;
            rx_data <= 8'd0;
            rx_valid <= 1'b0;
            rx_overrun <= 1'b0;

            done <= 1'b0;
            rdata <= 16'd0;
            rx_event_set <= 1'b0;
        end else begin
            done <= 1'b0;
            rdata <= 16'd0;
            rx_event_set <= 1'b0;

            // TX engine
            if (tx_busy) begin
                if (tx_baud_cnt != 16'd0) begin
                    tx_baud_cnt <= tx_baud_cnt - 16'd1;
                end else begin
                    tx_baud_cnt <= baud_div;
                    tx_shift <= {1'b1, tx_shift[9:1]};
                    tx_bit_cnt <= tx_bit_cnt + 4'd1;
                    uart_tx <= tx_shift[1];

                    if (tx_bit_cnt == 4'd9) begin
                        tx_busy <= 1'b0;
                        uart_tx <= 1'b1;
                    end
                end
            end

            // RX engine
            rx_sync <= {rx_sync[0], uart_rx};

            if (!rx_busy) begin
                if (rx_sync[1] && !rx_sync[0]) begin
                    rx_busy <= 1'b1;
                    rx_baud_cnt <= baud_div + {1'b0, baud_div[15:1]};
                    rx_bit_cnt <= 4'd0;
                end
            end else begin
                if (rx_baud_cnt != 16'd0) begin
                    rx_baud_cnt <= rx_baud_cnt - 16'd1;
                end else begin
                    rx_baud_cnt <= baud_div;

                    if (rx_bit_cnt < 4'd8) begin
                        rx_shift <= {rx_sync[1], rx_shift[7:1]};
                        rx_bit_cnt <= rx_bit_cnt + 4'd1;
                    end else begin
                        rx_busy <= 1'b0;
                        if (rx_valid) begin
                            rx_overrun <= 1'b1;
                        end else begin
                            rx_data <= rx_shift;
                            rx_valid <= 1'b1;
                            rx_event_set <= 1'b1;
                        end
                    end
                end
            end

            // Nonblocking command interface
            if (req) begin
                case (op)
                    UART_OP_STATUS: begin
                        // bit0=tx_ready, bit1=rx_valid, bit2=rx_overrun
                        rdata <= {13'd0, rx_overrun, rx_valid, tx_ready};
                        done <= 1'b1;
                    end

                    UART_OP_TX: begin
                        if (tx_ready) begin
                            tx_shift <= {1'b1, wdata[7:0], 1'b0};
                            tx_busy <= 1'b1;
                            tx_baud_cnt <= baud_div;
                            tx_bit_cnt <= 4'd0;
                            uart_tx <= 1'b0;
                            rdata <= 16'd1; // accepted
                        end else begin
                            rdata <= 16'd0; // not accepted
                        end
                        done <= 1'b1;
                    end

                    UART_OP_RX: begin
                        if (rx_valid) begin
                            rdata <= {1'b1, 7'd0, rx_data}; // valid flag + byte
                            rx_valid <= 1'b0;
                        end else begin
                            rdata <= 16'd0;
                        end
                        done <= 1'b1;
                    end

                    UART_OP_BAUD: begin
                        baud_div <= wdata;
                        rdata <= wdata;
                        done <= 1'b1;
                    end
                endcase
            end
        end
    end

endmodule

// Flat / no-instantiation memory interface.
// Area-focused version: Flash = QSPI continuous read, RAM = plain SPI read/write.
//
// Main area reductions versus initwait version:
//   - no 24-bit runtime address shift register
//   - no 16-bit runtime write-data shift register
//   - no 8-bit RAM command shift register
//   - no 8-bit flash mode shift register
//   - smaller state/counter registers
//   - smaller init wait counter for 50 MHz / 40 ms max default wait
//   - RAM reset/init removed to save area; RAM CS stays high during init
//
// CPU side:
//   spi_target = 0 -> Flash read only, byte address {7'b0, addr, 1'b0}
//   spi_target = 1 -> RAM read/write, byte address {1'b0, 6'b0, addr, 1'b0}
//
// External bus pins:
//   Flash QSPI uses IO[3:0].
//   RAM SPI uses IO0 = MOSI and IO1 = MISO. IO2/IO3 are released for RAM.
//

module qspi_memory_interface (
    input  wire        clk,
    input  wire        spi_rst_n,

    input  wire        st,
    input  wire        ld,
    input  wire        spi_target,    // 0 = flash, 1 = RAM
    input  wire [15:0] addr,
    input  wire [15:0] data_in,
    output reg  [15:0] data_out,

    output wire        spi_clk,
    output wire        spi_flash_cs,  // active low
    output wire        spi_ram_cs,    // active low

    input  wire [3:0]  spi_data_in,
    output wire [3:0]  spi_data_out,
    output wire [3:0]  spi_data_oe,

    output reg         busy,
    output wire ready,
    output wire init_done_dbg
  );

  // ============================================================
  // 0) Shared output mux: init owns pins until init_done = 1
  // ============================================================

  wire init_done;

  reg        init_spi_clk;
  reg        init_flash_cs;
  reg        init_ram_cs;
  reg [3:0]  init_data_out;
  reg [3:0]  init_data_oe;

  reg        core_spi_clk;
  reg        core_flash_cs;
  reg        core_ram_cs;
  reg [3:0]  core_data_out;
  reg [3:0]  core_data_oe;

  assign spi_clk      = init_done ? core_spi_clk   : init_spi_clk;
  assign spi_flash_cs = init_done ? core_flash_cs  : init_flash_cs;
  assign spi_ram_cs   = init_done ? core_ram_cs    : init_ram_cs;
  assign spi_data_out = init_done ? core_data_out  : init_data_out;
  assign spi_data_oe  = init_done ? core_data_oe   : init_data_oe;
  assign init_done_dbg = init_done;
  assign ready = init_done && (wstate == W_IDLE) && !core_busy;
  // ============================================================
  // 1) CPU 16-bit word wrapper FSM
  // ============================================================

  localparam W_IDLE       = 2'd0;
  localparam W_START      = 2'd1;
  localparam W_WAIT_BUSY  = 2'd2;
  localparam W_WAIT_IDLE  = 2'd3;

  reg [1:0]  wstate;
  reg        op_is_read;
  reg [15:0] core_addr_cpu;
  reg [15:0] core_write_word;
  reg        core_start_read;
  reg        core_start_write;
  reg        core_target_ram;

  wire [15:0] core_read_word;
  wire        core_busy;

  always @(posedge clk or negedge spi_rst_n)
  begin
    if (!spi_rst_n)
    begin
      wstate           <= W_IDLE;
      busy             <= 1'b0;
      op_is_read       <= 1'b0;
      core_addr_cpu    <= 16'h0000;
      core_write_word  <= 16'h0000;
      core_start_read  <= 1'b0;
      core_start_write <= 1'b0;
      core_target_ram  <= 1'b0;
      data_out         <= 16'h0000;
    end
    else
    begin
      core_start_read  <= 1'b0;
      core_start_write <= 1'b0;

      case (wstate)
        W_IDLE:
        begin
          busy <= !init_done;

          if (!init_done)
          begin
            wstate <= W_IDLE;
          end
          else if (ld)
          begin
            busy            <= 1'b1;
            op_is_read      <= 1'b1;
            core_target_ram <= spi_target;
            core_addr_cpu   <= addr;
            wstate          <= W_START;
          end
          else if (st)
          begin
            // Flash writing is intentionally blocked here.
            // RAM writes are SPI only.
            if (spi_target)
            begin
              busy             <= 1'b1;
              op_is_read       <= 1'b0;
              core_target_ram  <= 1'b1;
              core_addr_cpu    <= addr;
              core_write_word  <= data_in;
              wstate           <= W_START;
            end
            else
            begin
              busy   <= 1'b0;
              wstate <= W_IDLE;
            end
          end
        end

        W_START:
        begin
          busy <= 1'b1;
          if (op_is_read)
            core_start_read <= 1'b1;
          else
            core_start_write <= 1'b1;
          wstate <= W_WAIT_BUSY;
        end

        W_WAIT_BUSY:
        begin
          busy <= 1'b1;
          if (core_busy)
            wstate <= W_WAIT_IDLE;
        end

        W_WAIT_IDLE:
        begin
          if (!core_busy)
          begin
            if (op_is_read)
              data_out <= core_read_word;
            busy       <= 1'b0;
            op_is_read <= 1'b0;
            wstate     <= W_IDLE;
          end
          else
          begin
            busy <= 1'b1;
          end
        end
      endcase
    end
  end

  // ============================================================
  // 2) Startup initializer FSM
  // ============================================================

  localparam I_IDLE       = 3'd0;
  localparam I_WAIT_PWR   = 3'd1;
  localparam I_LOAD       = 3'd2;
  localparam I_SHIFT_LOW  = 3'd3;
  localparam I_SHIFT_HIGH = 3'd4;
  localparam I_CS_HIGH    = 3'd5;
  localparam I_GAP        = 3'd6;
  localparam I_DONE       = 3'd7;

  localparam INIT_STEP_FLASH_RST_EN = 4'd0;
  localparam INIT_STEP_FLASH_RST    = 4'd1;
  localparam INIT_STEP_FLASH_WREN   = 4'd2;
  localparam INIT_STEP_FLASH_SR2    = 4'd3;
  localparam INIT_STEP_FLASH_EB     = 4'd4;
  localparam INIT_STEP_FLASH_CONT   = 4'd5;
  localparam INIT_STEP_END          = 4'd6;

  // Default waits fit in 22 bits at 50 MHz:
  // 40 ms = 2,000,000 cycles. If you increase INIT_CLK_HZ a lot,
  // increase INIT_WAIT_BITS too.
  localparam integer INIT_CLK_HZ      = 1;
  localparam integer INIT_WAIT_BITS   = 22;
  `ifdef COCOTB_SIM_FAST_INIT
  localparam [INIT_WAIT_BITS-1:0] INIT_POWER_WAIT_CYCLES      = 22'd02;
  localparam [INIT_WAIT_BITS-1:0] INIT_RESET_WAIT_CYCLES      = 22'd02;
  localparam [INIT_WAIT_BITS-1:0] INIT_FLASH_SR2_WAIT_CYCLES  = 22'd02;
  localparam [INIT_WAIT_BITS-1:0] INIT_FLASH_CONT_WAIT_CYCLES = 22'd02;
  localparam [INIT_WAIT_BITS-1:0] INIT_CMD_GAP_CYCLES         = 22'd02;
  `else
      localparam [INIT_WAIT_BITS-1:0] INIT_POWER_WAIT_CYCLES      = (INIT_CLK_HZ / 1000) * 10;
      localparam [INIT_WAIT_BITS-1:0] INIT_RESET_WAIT_CYCLES      = (INIT_CLK_HZ / 1000) * 2;
      localparam [INIT_WAIT_BITS-1:0] INIT_FLASH_SR2_WAIT_CYCLES  = (INIT_CLK_HZ / 1000) * 40;
      localparam [INIT_WAIT_BITS-1:0] INIT_FLASH_CONT_WAIT_CYCLES = (INIT_CLK_HZ / 1000) * 1;
      localparam [INIT_WAIT_BITS-1:0] INIT_CMD_GAP_CYCLES         = (INIT_CLK_HZ / 1000000) * 5 + 4;
  `endif

  function [INIT_WAIT_BITS-1:0] init_gap_cycles;
    input [3:0] stp;
    begin
      case (stp)
        INIT_STEP_FLASH_RST:
          init_gap_cycles = INIT_RESET_WAIT_CYCLES;
        INIT_STEP_FLASH_SR2:
          init_gap_cycles = INIT_FLASH_SR2_WAIT_CYCLES;
        INIT_STEP_FLASH_CONT:
          init_gap_cycles = INIT_FLASH_CONT_WAIT_CYCLES;
        default:
          init_gap_cycles = INIT_CMD_GAP_CYCLES;
      endcase
    end
  endfunction

  function [2:0] init_bytes_left;
    input [3:0] stp;
    begin
      case (stp)
        INIT_STEP_FLASH_SR2:
          init_bytes_left = 3'd2;
        INIT_STEP_FLASH_CONT:
          init_bytes_left = 3'd6;
        INIT_STEP_END:
          init_bytes_left = 3'd0;
        default:
          init_bytes_left = 3'd1;
      endcase
    end
  endfunction

  function [7:0] init_byte;
    input [3:0] stp;
    input [2:0] idx;
    begin
      case (stp)
        INIT_STEP_FLASH_RST_EN:
          init_byte = 8'h66;
        INIT_STEP_FLASH_RST:
          init_byte = 8'h99;
        INIT_STEP_FLASH_WREN:
          init_byte = 8'h06;
        INIT_STEP_FLASH_SR2:
          init_byte = (idx == 3'd0) ? 8'h31 : 8'h02;
        INIT_STEP_FLASH_EB:
          init_byte = 8'hEB;
        INIT_STEP_FLASH_CONT:
        begin
          case (idx)
            3'd0:
              init_byte = 8'h00; // addr[23:16]
            3'd1:
              init_byte = 8'h00; // addr[15:8]
            3'd2:
              init_byte = 8'h00; // addr[7:0]
            3'd3:
              init_byte = 8'hA0; // continuous-read mode bits
            default:
              init_byte = 8'h00; // dummy clocks
          endcase
        end
        default:
          init_byte = 8'h00;
      endcase
    end
  endfunction

  reg [2:0]  init_state;
  reg [3:0]  init_step;
  reg [7:0]  init_shift;
  reg [2:0]  init_bit_cnt;
  reg [INIT_WAIT_BITS-1:0] init_wait_cnt;
  reg [2:0]  init_byte_idx;
  reg        init_done_r;

  wire       init_use_quad_w   = (init_step == INIT_STEP_FLASH_CONT);
  wire [2:0] init_bytes_left_w = init_bytes_left(init_step);

  assign init_done = init_done_r;

  always @(posedge clk or negedge spi_rst_n)
  begin
    if (!spi_rst_n)
    begin
      init_state    <= I_IDLE;
      init_step     <= INIT_STEP_FLASH_RST_EN;
      init_done_r   <= 1'b0;
      init_spi_clk  <= 1'b0;
      init_flash_cs <= 1'b1;
      init_ram_cs   <= 1'b1;
      init_data_out <= 4'b0000;
      init_data_oe  <= 4'b0000;
      init_shift    <= 8'h00;
      init_bit_cnt  <= 3'd0;
      init_wait_cnt <= {INIT_WAIT_BITS{1'b0}};
      init_byte_idx <= 3'd0;
    end
    else
    begin
      case (init_state)
        I_IDLE:
        begin
          init_done_r   <= 1'b0;
          init_spi_clk  <= 1'b0;
          init_flash_cs <= 1'b1;
          init_ram_cs   <= 1'b1;
          init_data_oe  <= 4'b0000;
          init_wait_cnt <= INIT_POWER_WAIT_CYCLES;
          init_state    <= I_WAIT_PWR;
        end

        I_WAIT_PWR:
        begin
          if (init_wait_cnt != {INIT_WAIT_BITS{1'b0}})
            init_wait_cnt <= init_wait_cnt - {{(INIT_WAIT_BITS-1){1'b0}}, 1'b1};
          else
            init_state <= I_LOAD;
        end

        I_LOAD:
        begin
          if (init_step >= INIT_STEP_END)
          begin
            init_state <= I_DONE;
          end
          else
          begin
            init_spi_clk  <= 1'b0;
            init_flash_cs <= 1'b0;
            init_ram_cs   <= 1'b1;
            init_byte_idx <= 3'd0;
            init_shift    <= init_byte(init_step, 3'd0);
            init_bit_cnt  <= init_use_quad_w ? 3'd1 : 3'd7;
            init_state    <= I_SHIFT_LOW;
          end
        end

        I_SHIFT_LOW:
        begin
          init_spi_clk <= 1'b0;
          if (init_use_quad_w)
          begin
            init_data_oe  <= 4'b1111;
            init_data_out <= init_shift[7:4];
          end
          else
          begin
            // SPI command: IO0 = MOSI, IO1 = MISO released.
            init_data_oe  <= 4'b0001;
            init_data_out <= {3'b000, init_shift[7]};
          end
          init_state <= I_SHIFT_HIGH;
        end

        I_SHIFT_HIGH:
        begin
          init_spi_clk <= 1'b1;
          if (init_bit_cnt == 3'd0)
          begin
            if (init_byte_idx + 3'd1 >= init_bytes_left_w)
            begin
              init_state <= I_CS_HIGH;
            end
            else
            begin
              init_byte_idx <= init_byte_idx + 3'd1;
              init_shift    <= init_byte(init_step, init_byte_idx + 3'd1);
              init_bit_cnt  <= init_use_quad_w ? 3'd1 : 3'd7;
              init_state    <= I_SHIFT_LOW;
            end
          end
          else
          begin
            if (init_use_quad_w)
              init_shift <= {init_shift[3:0], 4'h0};
            else
              init_shift <= {init_shift[6:0], 1'b0};
            init_bit_cnt <= init_bit_cnt - 3'd1;
            init_state   <= I_SHIFT_LOW;
          end
        end

        I_CS_HIGH:
        begin
          init_spi_clk <= 1'b0;
          init_data_oe <= 4'b0000;

          // Keep flash CS low between EBh command and the quad address/mode/dummy part.
          if (init_step == INIT_STEP_FLASH_EB)
          begin
            init_flash_cs <= 1'b0;
            init_ram_cs   <= 1'b1;
            init_step     <= INIT_STEP_FLASH_CONT;
            init_state    <= I_LOAD;
          end
          else
          begin
            init_flash_cs <= 1'b1;
            init_ram_cs   <= 1'b1;
            init_wait_cnt <= init_gap_cycles(init_step);
            init_state    <= I_GAP;
          end
        end

        I_GAP:
        begin
          if (init_wait_cnt != {INIT_WAIT_BITS{1'b0}})
            init_wait_cnt <= init_wait_cnt - {{(INIT_WAIT_BITS-1){1'b0}}, 1'b1};
          else
          begin
            init_step  <= init_step + 4'd1;
            init_state <= I_LOAD;
          end
        end

        I_DONE:
        begin
          init_done_r   <= 1'b1;
          init_spi_clk  <= 1'b0;
          init_flash_cs <= 1'b1;
          init_ram_cs   <= 1'b1;
          init_data_oe  <= 4'b0000;
        end
      endcase
    end
  end

  // ============================================================
  // 3) Runtime memory core
  // ============================================================

  localparam C_IDLE        = 4'd0;
  localparam C_FLASH_ADDR  = 4'd1;
  localparam C_FLASH_MODE  = 4'd2;
  localparam C_FLASH_DUMMY = 4'd3;
  localparam C_FLASH_DATA  = 4'd4;
  localparam C_RAM_CMD     = 4'd5;
  localparam C_RAM_ADDR    = 4'd6;
  localparam C_RAM_DATA    = 4'd7;
  localparam C_FINISH      = 4'd8;

  reg [3:0]  core_state;
  reg        core_is_writing;
  reg [15:0] core_read_shift;
  reg [4:0]  core_count;
  reg [15:0] core_read_word_r;

  assign core_busy      = (core_state != C_IDLE);
  assign core_read_word = core_read_word_r;

  // Address mapping. CPU address is word address, external memory is byte address.
  wire [23:0] flash_byte_addr = {7'b0000000, core_addr_cpu, 1'b0};
  wire [23:0] ram_byte_addr   = {1'b0, 6'b000000, core_addr_cpu, 1'b0};

  wire ram_cmd_mosi = (core_count == 5'd1) ||
       ((core_count == 5'd0) && !core_is_writing); // write=02h, read=03h

  always @(posedge clk or negedge spi_rst_n)
  begin
    if (!spi_rst_n)
    begin
      core_state       <= C_IDLE;
      core_spi_clk     <= 1'b0;
      core_flash_cs    <= 1'b1;
      core_ram_cs      <= 1'b1;
      core_data_oe     <= 4'b0000;
      core_is_writing  <= 1'b0;
      core_read_shift  <= 16'h0000;
      core_count       <= 5'd0;
      core_read_word_r <= 16'h0000;
    end
    else if (!init_done)
    begin
      core_state     <= C_IDLE;
      core_spi_clk   <= 1'b0;
      core_flash_cs  <= 1'b1;
      core_ram_cs    <= 1'b1;
      core_data_oe   <= 4'b0000;
    end
    else
    begin
      if (core_state == C_IDLE)
      begin
        core_spi_clk  <= 1'b0;
        core_data_oe  <= 4'b0000;
        core_flash_cs <= 1'b1;
        core_ram_cs   <= 1'b1;

        if (core_start_read || core_start_write)
        begin
          core_is_writing <= core_start_write;
          core_read_shift <= 16'h0000;

          if (core_target_ram)
          begin
            // RAM stays plain SPI.
            core_flash_cs <= 1'b1;
            core_ram_cs   <= 1'b0;
            core_data_oe  <= 4'b0001; // IO0 MOSI only
            core_count    <= 5'd7;    // 8 SPI command bits
            core_state    <= C_RAM_CMD;
          end
          else
          begin
            // Flash is already in continuous QSPI read mode.
            core_flash_cs <= 1'b0;
            core_ram_cs   <= 1'b1;
            core_data_oe  <= 4'b1111;
            core_count    <= 5'd5; // 6 QSPI address nibbles
            core_state    <= C_FLASH_ADDR;
          end
        end
      end
      else if (core_state == C_FINISH)
      begin
        // Hold CS low for one extra system clock with SCK low, then release.
        core_spi_clk    <= 1'b0;
        core_data_oe    <= 4'b0000;
        core_flash_cs   <= 1'b1;
        core_ram_cs     <= 1'b1;
        core_is_writing <= 1'b0;
        core_state      <= C_IDLE;
      end
      else
      begin
        // Two system clocks per external SPI/QSPI clock.
        core_spi_clk <= !core_spi_clk;

        // Advance/sample on the high phase just before we drive SCK low.
        if (core_spi_clk)
        begin
          case (core_state)
            C_FLASH_ADDR:
            begin
              if (core_count == 5'd0)
              begin
                core_count <= 5'd1; // 2 QSPI mode nibbles: A,0
                core_state <= C_FLASH_MODE;
              end
              else
              begin
                core_count <= core_count - 5'd1;
              end
            end

            C_FLASH_MODE:
            begin
              if (core_count == 5'd0)
              begin
                core_data_oe <= 4'b0000;
                core_count   <= 5'd3; // 4 QSPI dummy clocks
                core_state   <= C_FLASH_DUMMY;
              end
              else
              begin
                core_count <= core_count - 5'd1;
              end
            end

            C_FLASH_DUMMY:
            begin
              if (core_count == 5'd0)
              begin
                core_count <= 5'd3; // 4 QSPI data clocks = 16 bits
                core_state <= C_FLASH_DATA;
              end
              else
              begin
                core_count <= core_count - 5'd1;
              end
            end

            C_FLASH_DATA:
            begin
              core_read_shift <= {core_read_shift[11:0], spi_data_in};
              if (core_count == 5'd0)
              begin
                core_read_word_r <= {core_read_shift[11:0], spi_data_in};
                core_state       <= C_FINISH;
              end
              else
              begin
                core_count <= core_count - 5'd1;
              end
            end

            C_RAM_CMD:
            begin
              if (core_count == 5'd0)
              begin
                core_count <= 5'd23; // 24 SPI address bits
                core_state <= C_RAM_ADDR;
              end
              else
              begin
                core_count <= core_count - 5'd1;
              end
            end

            C_RAM_ADDR:
            begin
              if (core_count == 5'd0)
              begin
                core_count <= 5'd15; // 16 data bits
                core_state <= C_RAM_DATA;
                if (core_is_writing)
                  core_data_oe <= 4'b0001; // keep driving MOSI
                else
                  core_data_oe <= 4'b0000; // release bus, RAM drives IO1/MISO
              end
              else
              begin
                core_count <= core_count - 5'd1;
              end
            end

            C_RAM_DATA:
            begin
              if (core_is_writing)
              begin
                if (core_count == 5'd0)
                begin
                  core_state <= C_FINISH;
                end
                else
                begin
                  core_count <= core_count - 5'd1;
                end
              end
              else
              begin
                core_read_shift <= {core_read_shift[14:0], spi_data_in[1]};
                if (core_count == 5'd0)
                begin
                  core_read_word_r <= {core_read_shift[14:0], spi_data_in[1]};
                  core_state       <= C_FINISH;
                end
                else
                begin
                  core_count <= core_count - 5'd1;
                end
              end
            end

            default:
            begin
              core_state <= C_FINISH;
            end
          endcase
        end
      end
    end
  end

  always @(*)
  begin
    core_data_out = 4'b1111;

    case (core_state)
      C_FLASH_ADDR:
      begin
        case (core_count)
          5'd5:
            core_data_out = flash_byte_addr[23:20];
          5'd4:
            core_data_out = flash_byte_addr[19:16];
          5'd3:
            core_data_out = flash_byte_addr[15:12];
          5'd2:
            core_data_out = flash_byte_addr[11:8];
          5'd1:
            core_data_out = flash_byte_addr[7:4];
          default:
            core_data_out = flash_byte_addr[3:0];
        endcase
      end

      C_FLASH_MODE:
      begin
        core_data_out = (core_count == 5'd1) ? 4'hA : 4'h0;
      end

      C_FLASH_DUMMY:
      begin
        core_data_out = 4'b1111;
      end

      C_FLASH_DATA:
      begin
        core_data_out = 4'b1111;
      end

      C_RAM_CMD:
      begin
        // RAM SPI MOSI on IO0. IO1/2/3 are released by OE.
        core_data_out = {3'b111, ram_cmd_mosi};
      end

      C_RAM_ADDR:
      begin
        core_data_out = {3'b111, ram_byte_addr[core_count]};
      end

      C_RAM_DATA:
      begin
        if (core_is_writing)
          core_data_out = {3'b111, core_write_word[core_count]};
        else
          core_data_out = 4'b1111;
      end

      default:
      begin
        core_data_out = 4'b1111;
      end
    endcase
  end

endmodule


module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module tt_um_trip_cpu (
  input [7:0] ui_in,
  input clk,
  input ena,
  input rst_n,
  input [7:0] uio_in,
  output [7:0] uo_out,
  output [7:0] uio_out,
  output [7:0] uio_oe
);
  wire s0;
  wire [2:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire s4;
  wire [2:0] s5;
  wire [15:0] s6;
  wire [15:0] s7;
  wire s8;
  wire [15:0] s9;
  wire s10;
  wire [15:0] s11;
  wire s12;
  wire s13;
  wire [2:0] s14;
  wire s15;
  wire s16;
  wire [2:0] s17;
  wire s18;
  wire [2:0] s19;
  wire [7:0] s20;
  wire s21;
  wire [15:0] s22;
  wire s23;
  wire [15:0] s24;
  wire s25;
  wire [15:0] s26;
  wire s27;
  wire s28;
  wire s29;
  wire [15:0] s30;
  wire [15:0] s31;
  wire s32;
  wire [1:0] s33;
  wire [2:0] s34;
  wire s35;
  wire s36;
  wire [1:0] s37;
  wire [15:0] s38;
  wire s39;
  wire [15:0] s40;
  wire s41;
  wire [15:0] s42;
  wire s43;
  wire [15:0] s44;
  wire s45;
  wire s46;
  wire s47;
  wire [15:0] s48;
  wire [15:0] s49;
  wire s50;
  wire [1:0] s51;
  wire [2:0] s52;
  wire s53;
  wire s54;
  wire [1:0] s55;
  wire [15:0] s56;
  wire s57;
  wire [15:0] s58;
  wire s59;
  wire s60;
  wire [15:0] s61;
  wire s62;
  wire s63;
  wire s64;
  wire [15:0] s65;
  wire [15:0] s66;
  wire \sda-in ;
  wire spics_flash;
  wire spi_clock;
  wire spics_ram;
  wire [3:0] qspi_data_oe;
  wire [3:0] qspi_data_in;
  wire [3:0] qspi_data_out;
  wire [7:0] s67;
  wire s68;
  wire s69;
  wire s70;
  wire s71;
  wire s72;
  assign qspi_data_in[0] = uio_in[1];
  assign qspi_data_in[1] = uio_in[2];
  assign qspi_data_in[2] = uio_in[4];
  assign qspi_data_in[3] = uio_in[5];
  assign \sda-in  = uio_in[7];
  assign s68 = ui_in[7];
  // shared_alu_arbiter3
  shared_alu_arbiter3 shared_alu_arbiter3_i0 (
    .clk( clk ),
    .rst_n( rst_n ),
    .req0( s0 ),
    .op0( s1 ),
    .a0( s2 ),
    .b0( s3 ),
    .req1( s4 ),
    .op1( s5 ),
    .a1( s6 ),
    .b1( s7 ),
    .done0( s8 ),
    .result0( s9 ),
    .done1( s10 ),
    .result1( s11 )
  );
  // shared_event_unit3
  shared_event_unit3 shared_event_unit3_i1 (
    .clk( clk ),
    .rst_n( rst_n ),
    .set0( s12 ),
    .clr0( s13 ),
    .id0( s14 ),
    .set1( s15 ),
    .clr1( s16 ),
    .id1( s17 ),
    .set2( s18 ),
    .clr2( 1'b0 ),
    .id2( s19 ),
    .event_flags( s20 )
  );
  // tiny_core
  tiny_core tiny_core_i2 (
    .RESET_PC( 16'b10 ),
    .clk( clk ),
    .rst_n( rst_n ),
    .core_en( rst_n ),
    .alu_done( s8 ),
    .alu_result( s9 ),
    .mem_done( s21 ),
    .mem_rdata( s22 ),
    .event_flags( s20 ),
    .pin_done( s23 ),
    .pin_rdata( s24 ),
    .uart_done( s25 ),
    .uart_rdata( s26 ),
    .alu_req( s0 ),
    .alu_op( s1 ),
    .alu_a( s2 ),
    .alu_b( s3 ),
    .mem_req( s27 ),
    .mem_write( s28 ),
    .mem_target( s29 ),
    .mem_addr( s30 ),
    .mem_wdata( s31 ),
    .event_set( s12 ),
    .event_clr( s13 ),
    .event_id( s14 ),
    .pin_req( s32 ),
    .pin_op( s33 ),
    .pin_id( s34 ),
    .pin_wdata( s35 ),
    .uart_req( s36 ),
    .uart_op( s37 ),
    .uart_wdata( s38 )
  );
  // tiny_core
  tiny_core tiny_core_i3 (
    .RESET_PC( 16'b11 ),
    .clk( clk ),
    .rst_n( rst_n ),
    .core_en( rst_n ),
    .alu_done( s10 ),
    .alu_result( s11 ),
    .mem_done( s39 ),
    .mem_rdata( s40 ),
    .event_flags( s20 ),
    .pin_done( s41 ),
    .pin_rdata( s42 ),
    .uart_done( s43 ),
    .uart_rdata( s44 ),
    .alu_req( s4 ),
    .alu_op( s5 ),
    .alu_a( s6 ),
    .alu_b( s7 ),
    .mem_req( s45 ),
    .mem_write( s46 ),
    .mem_target( s47 ),
    .mem_addr( s48 ),
    .mem_wdata( s49 ),
    .event_set( s15 ),
    .event_clr( s16 ),
    .event_id( s17 ),
    .pin_req( s50 ),
    .pin_op( s51 ),
    .pin_id( s52 ),
    .pin_wdata( s53 ),
    .uart_req( s54 ),
    .uart_op( s55 ),
    .uart_wdata( s56 )
  );
  // shared_spi_mem_arbiter3
  shared_spi_mem_arbiter3 shared_spi_mem_arbiter3_i4 (
    .clk( clk ),
    .rst_n( rst_n ),
    .req0( s27 ),
    .write0( s28 ),
    .target0( s29 ),
    .addr0( s30 ),
    .wdata0( s31 ),
    .req1( s45 ),
    .write1( s46 ),
    .target1( s47 ),
    .addr1( s48 ),
    .wdata1( s49 ),
    .req2( s45 ),
    .write2( s46 ),
    .target2( s47 ),
    .addr2( s48 ),
    .wdata2( s49 ),
    .spi_ready( s57 ),
    .spi_data_out( s58 ),
    .spi_busy( s59 ),
    .done0( s21 ),
    .rdata0( s22 ),
    .done1( s39 ),
    .rdata1( s40 ),
    .done2( s60 ),
    .rdata2( s61 ),
    .spi_st( s62 ),
    .spi_ld( s63 ),
    .spi_target( s64 ),
    .spi_addr( s65 ),
    .spi_data_in( s66 )
  );
  // shared_pin_controller3
  shared_pin_controller3 shared_pin_controller3_i5 (
    .clk( clk ),
    .rst_n( rst_n ),
    .gpio_in( ui_in ),
    .req0( s32 ),
    .op0( s33 ),
    .pin0( s34 ),
    .wdata0( s35 ),
    .req1( s50 ),
    .op1( s51 ),
    .pin1( s52 ),
    .wdata1( s53 ),
    .gpio_out( s67 ),
    .done0( s23 ),
    .rdata0( s24 ),
    .done1( s41 ),
    .rdata1( s42 )
  );
  // shared_uart_controller2_event
  shared_uart_controller2_event shared_uart_controller2_event_i6 (
    .clk( clk ),
    .rst_n( rst_n ),
    .uart_rx( s68 ),
    .req0( s36 ),
    .op0( s37 ),
    .wdata0( s38 ),
    .req1( s54 ),
    .op1( s55 ),
    .wdata1( s56 ),
    .uart_tx( s69 ),
    .uart_tx_oe( s70 ),
    .uart_event_set( s18 ),
    .uart_event_id( s19 ),
    .done0( s25 ),
    .rdata0( s26 ),
    .done1( s43 ),
    .rdata1( s44 )
  );
  // qspi_memory_interface
  qspi_memory_interface qspi_memory_interface_i7 (
    .clk( clk ),
    .spi_rst_n( rst_n ),
    .st( s62 ),
    .ld( s63 ),
    .spi_target( s64 ),
    .addr( s65 ),
    .data_in( s66 ),
    .spi_data_in( qspi_data_in ),
    .data_out( s58 ),
    .spi_clk( spi_clock ),
    .spi_flash_cs( spics_flash ),
    .spi_ram_cs( spics_ram ),
    .spi_data_out( qspi_data_out ),
    .spi_data_oe( qspi_data_oe ),
    .busy( s59 ),
    .ready( s57 )
  );
  assign uio_out[0] = spics_flash;
  assign uio_out[1] = qspi_data_out[0];
  assign uio_out[2] = qspi_data_out[1];
  assign uio_out[3] = spi_clock;
  assign uio_out[4] = qspi_data_out[2];
  assign uio_out[5] = qspi_data_out[3];
  assign uio_out[6] = spics_ram;
  assign uio_out[7] = 1'b1;
  assign uio_oe[0] = 1'b1;
  assign uio_oe[1] = qspi_data_oe[0];
  assign uio_oe[2] = qspi_data_oe[1];
  assign uio_oe[3] = 1'b1;
  assign uio_oe[4] = qspi_data_oe[2];
  assign uio_oe[5] = qspi_data_oe[3];
  assign uio_oe[6] = 1'b1;
  assign uio_oe[7] = 1'b1;
  assign s71 = s67[7];
  Mux_2x1 Mux_2x1_i8 (
    .sel( s70 ),
    .in_0( s71 ),
    .in_1( s69 ),
    .out( s72 )
  );
  assign uo_out[6:0] = s67[6:0];
  assign uo_out[7] = s72;
endmodule
